# Generated by Django 6.1.1 on 2026-09-27 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaccion',
            name='tipo',
            field=models.CharField(choices=[('', 'Seleccione una opción'), ('ingreso', 'Ingreso'), ('egreso', 'Egreso')], max_length=10),
        ),
    ]
