# Generated by Django 6.1.1 on 2026-09-28 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_alter_transaccion_tipo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'ordering': ['nombre'], 'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.AlterModelOptions(
            name='cuenta',
            options={'verbose_name': 'Cuenta', 'verbose_name_plural': 'Cuentas'},
        ),
        migrations.AlterModelOptions(
            name='transaccion',
            options={'ordering': ['-fecha', '-pk'], 'verbose_name': 'Transacción', 'verbose_name_plural': 'Transacciones'},
        ),
    ]
